services:
  postgres:
    image: postgres:alpine
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: imbo_test
      POSTGRES_PASSWORD: imbo_test
    volumes:
      - ./setup:/docker-entrypoint-initdb.d

  adminer:
    depends_on:
      - postgres
    image: adminer:latest
    ports:
      - "8888:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  pgadmin:
