services:
  postgres:
    image: postgres:alpine
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: imbo_test
      POSTGRES_PASSWORD: imbo_test
    volumes:
      - ./setup:/docker-entrypoint-initdb.d

  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: imbo_test
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgadmin:
