name: CI
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["8.3"]

    name: Run CI build

    services:
      postgresql:
        image: postgres
        env:
          POSTGRES_USER: imbo_test
          POSTGRES_PASSWORD: imbo_test
        ports:
          - 5555:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: imagick

      - name: PHP version
        run: php -v

      - name: PHP info
        run: php -i

      - name: PHP modules
        run: php -m

      - name: Create tables
        run: psql postgresql://imbo_test:imbo_test@127.0.0.1:5555/imbo_test -f ./setup/000-imbo.sql

      - name: Validate composer files
        run: composer validate --strict

      - name: Get Composer Cache Directory
        id: composer-cache-dir
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-composer-

      - name: Install dependencies
        run: composer install

      - name: Run unit tests
        run: vendor/bin/phpunit

      - name: Run static code analysis
        run: vendor/bin/phpstan analyse

      - name: Check coding standard
        run: PHP_CS_FIXER_IGNORE_ENV=1 vendor/bin/php-cs-fixer fix --dry-run --diff
